apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  labels:
    app: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
      - image: owasp/zap2docker-bare
        name: zap
