apiVersion: v1
kind: Service
metadata:
  labels:
    app: zap
  name: zap
  namespace: default
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    app: zap
  type: NodePort